on:
    push:
        branches:
          - master
          - "release/**"
        paths:
          - "src/**" 
    pull_request:      
        branches:
          - master
          - "release/**"
jobs:
    test:          
       runs-on: ubunto-latest
       steps:
       - name: Checkout
         uses: actions/checkout@v4.2.2
        
       - name: Run tests
         run: nmp test  


